# Generated by Django 3.1 on 2021-09-16 13:28

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_770_340', models.ImageField(upload_to='images/automobiles', verbose_name='picture 770x340')),
                ('availability_hybrid', models.BooleanField(default=False)),
                ('price_starts', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField()),
                ('picture_1920_1080', models.ImageField(upload_to='images/slider', verbose_name='picture 1920x1080')),
                ('picture_1024_768', models.ImageField(upload_to='images/slider', verbose_name='picture 1024x768')),
                ('picture_1280_1024', models.ImageField(upload_to='images/slider', verbose_name='picture 1280x1024')),
                ('picture_2560_1080', models.ImageField(upload_to='images/slider', verbose_name='picture 2560x1080')),
                ('picture_1920_1080_ru', models.ImageField(default='', upload_to='images/slider', verbose_name='picture 1920x1080 RU')),
                ('picture_1024_768_ru', models.ImageField(default='', upload_to='images/slider', verbose_name='picture 1024x768 RU')),
                ('picture_1280_1024_ru', models.ImageField(default='', upload_to='images/slider', verbose_name='picture 1280x1024 RU')),
                ('picture_2560_1080_ru', models.ImageField(default='', upload_to='images/slider', verbose_name='picture 2560x1080 RU')),
            ],
            options={
                'verbose_name_plural': 'Слайдер на главной странице старый',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(default=datetime.date.today)),
                ('picture_563_266', models.ImageField(default='images\\news1.jpg', upload_to='images/news_and_promotion', verbose_name='picture 563x266')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField(default=datetime.date.today)),
                ('picture_563_266', models.ImageField(default='images\\news1.jpg', upload_to='images/news_and_promotion', verbose_name='picture 563x266')),
            ],
            options={
                'verbose_name_plural': 'Акции',
                'ordering': ['publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='about.languages')),
                ('title_description', models.CharField(max_length=54)),
                ('news', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.news')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=138)),
                ('short_description', models.CharField(default='', max_length=138)),
                ('text', ckeditor.fields.RichTextField(default='')),
                ('Promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.promotion')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.languages')),
            ],
            options={
                'verbose_name_plural': 'Promotion_description',
                'unique_together': {('Promotion', 'language')},
            },
        ),
        migrations.CreateModel(
            name='News_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=138)),
                ('short_description', models.CharField(default='', max_length=138)),
                ('text', ckeditor.fields.RichTextField(default='')),
                ('News', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.news')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.languages')),
            ],
            options={
                'verbose_name_plural': 'News_description',
                'unique_together': {('News', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Automobiles_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=138)),
                ('Automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.automobiles')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.languages')),
            ],
            options={
                'verbose_name_plural': 'Automobiles_description',
                'unique_together': {('Automobile', 'language')},
            },
        ),
    ]
