# Generated by Django 3.1 on 2020-10-27 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture_770_340', models.ImageField(upload_to='images/automobiles')),
                ('availability_hybrid', models.BooleanField(default=False)),
                ('price_starts', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField()),
                ('picture_1920_1080', models.ImageField(upload_to='images/slider')),
                ('picture_1024_768', models.ImageField(upload_to='images/slider')),
                ('picture_1280_1024', models.ImageField(upload_to='images/slider')),
                ('picture_2560_1080', models.ImageField(upload_to='images/slider')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('publication_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('publication_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
