# Generated by Django 3.1 on 2020-11-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobiles',
            options={'verbose_name_plural': 'Automobiles'},
        ),
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name_plural': 'Main Slider'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name_plural': 'Promotion'},
        ),
        migrations.AddField(
            model_name='news',
            name='picture_563_266',
            field=models.ImageField(default='images\\news1.jpg', upload_to='images/news_and_promotion'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='picture_563_266',
            field=models.ImageField(default='images\\news1.jpg', upload_to='images/news_and_promotion'),
        ),
    ]
