# Generated by Django 3.1 on 2020-11-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20201109_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['publication_date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['publication_date'], 'verbose_name_plural': 'Promotion'},
        ),
    ]
