# Generated by Django 3.1 on 2021-09-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_mainslidernew_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainslidernew',
            options={'verbose_name_plural': 'Слайдер на главной странице'},
        ),
        migrations.CreateModel(
            name='MainSlider_description_New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=138)),
                ('short_description', models.CharField(default='', max_length=138)),
                ('text_button', models.CharField(default='', max_length=138)),
                ('Slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.mainslidernew')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.languages')),
            ],
            options={
                'verbose_name_plural': 'MainSlider_description',
                'unique_together': {('Slider', 'language')},
            },
        ),
    ]
