# Generated by Django 3.1 on 2020-11-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20201109_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobiles',
            name='price_starts',
            field=models.CharField(max_length=20),
        ),
    ]
