# Generated by Django 3.1 on 2021-10-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20211024_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine_type_description',
            name='class_name',
            field=models.CharField(default='', max_length=138),
        ),
        migrations.AddField(
            model_name='engine_volume_description',
            name='class_name',
            field=models.CharField(default='', max_length=138),
        ),
        migrations.AddField(
            model_name='transmission_description',
            name='class_name',
            field=models.CharField(default='', max_length=138),
        ),
        migrations.AddField(
            model_name='type_drive_description',
            name='class_name',
            field=models.CharField(default='', max_length=138),
        ),
    ]
