# Generated by Django 3.1 on 2020-12-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20201212_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(default='', max_length=138),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='short_description',
            field=models.CharField(default='', max_length=138),
        ),
    ]
