# Generated by Django 3.1 on 2021-01-25 16:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20210108_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='automobiles',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='title_ru',
        ),
        migrations.CreateModel(
            name='Short_description',
            fields=[
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='about.languages')),
                ('description', models.CharField(default='', max_length=138)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='about.languages')),
                ('text', ckeditor.fields.RichTextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='about.languages')),
                ('title_description', models.CharField(max_length=54)),
            ],
        ),
        migrations.AlterField(
            model_name='automobiles',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.short_description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.title'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='short_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.short_description'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.text'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.title'),
        ),
    ]
