# Generated by Django 3.1 on 2021-01-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20210125_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Automobiles_old',
        ),
        migrations.DeleteModel(
            name='News_old',
        ),
        migrations.DeleteModel(
            name='Promotion_old',
        ),
    ]
