# Generated by Django 3.1 on 2021-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auto_20210125_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='bubu',
            field=models.CharField(default='', max_length=50),
        ),
    ]
