# Generated by Django 3.1 on 2021-01-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_news_bubu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='bubu',
        ),
    ]
