# Generated by Django 3.1 on 2021-06-16 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_auto_20210129_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name_plural': 'Languages'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.CreateModel(
            name='News_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=138)),
                ('News', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.news')),
            ],
            options={
                'verbose_name_plural': 'News_description',
            },
        ),
    ]
