# Generated by Django 3.1 on 2021-06-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_auto_20210616_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_description',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.languages'),
            preserve_default=False,
        ),
    ]
