# Generated by Django 3.1 on 2021-06-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_news_description_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news_description',
            unique_together={('News', 'language')},
        ),
    ]
