# Generated by Django 3.1 on 2021-06-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_news_description_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_description',
            name='id',
        ),
        migrations.AlterField(
            model_name='news_description',
            name='language',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='about.languages'),
        ),
    ]
