# Generated by Django 3.1 on 2021-06-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_auto_20210616_1851'),
        ('about', '0017_auto_20210616_1801'),
    ]

    operations = [
    ]
